### ISSUE TITLE
White paper

### ISSUE THREAD

**Issue by g4s8** [cqfn/degitx#1]
Create a white paper document:
 - [x] Describe the problem
 - [x] Specify requirements
 - [x] Research other solutions
 - [x] Design architecture

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#25](https://github.com/cqfn/degitx/issues/25) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#46](https://github.com/cqfn/degitx/issues/46) is still not solved; solved: [#25](https://github.com/cqfn/degitx/issues/25).
