### ISSUE TITLE
Implement discovery protocol

### ISSUE THREAD

**Issue by g4s8** [cqfn/degitx#105]
Implement discovery protocol over metadata storage.
Initial version of discovery protocol will use metadata storage for keeping network to locator mappings.
The node register itself on startup by inserting self network address for locator ID into metadata storage. Later we may use local peer discovery for optimizations, or DHT for routing - keep it in mind when designing this protocol.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#124](https://github.com/cqfn/degitx/issues/124) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#124](https://github.com/cqfn/degitx/issues/124) is solved here.
