### ISSUE TITLE
Implement Gitaly gRPC services for push and fetch

### ISSUE THREAD

**Issue by g4s8** [cqfn/degitx#107]
Choose required gRPC services to be implemented for MVP. The initial version should support fetch and push operations. Decompose this ticket to smaller after investigation.

**Comment by kirill-h5i** [comment]
@stepanvalyavskiy I think we can choose only method required to push and pull from this list: https://github.com/cqfn/degitx/blob/master/docs/API_GITALY.md

**Comment by g4s8** [comment]
@stepanvalyavskiy we need to choose RPC methods to implement for the current milestone, but we'll start implementing this later.

**Comment by stepanvalyavskiy** [comment]
To fetch from and push to a single degitx node we have to implement:
- InfoRefsUploadPack
- InfoRefsReceivePack
- PostUploadPack
- PostReceivePack

**Comment by g4s8** [comment]
@stepanvalyavskiy thanks, created 4 tickets for them.
