### ISSUE TITLE
Import package under personal account

### ISSUE THREAD

**Issue by jeffzhu503** [cqfn/degitx#135]
I am wondering why https://github.com/g4s8/go-bundle is created and then import to degitx.  Why not create it as a public package directly in degitx? If other packages want to use it, they can import it from degitx.  
What might be the benefits doing this way?

**Comment by g4s8** [comment]
@jeffzhu503 this package is a general purpose package, it is not related to degitx project somehow, since it's responsible for arbitrary data binary marshalling.
