### ISSUE TITLE
Document issue in tech-report.pdf

### ISSUE THREAD

**Issue by jeffzhu503** [cqfn/degitx#143]
From the tech-report.pdf file: 
So what should be done to do an atomic commit on each git replica:
(1) receive git blobs for update
(2) queue references for update
(3) lock all reference objects that are going to be changed
(4) verify if reference update could be accepted (prepare for commit)
(5) if all participants are ready to commit (each replica in the prepared state), then commit, otherwise, abort
commit

Here are some confusions:
it says “do an atomic commit on each git replica”.  I think you mean “ do an atomic commit on the distributed git replicas”.
(1) **each replica** receives git blobs for update
(2) **each replica** queue references for update
(3) **each replica** lock all reference objects that are going to be changed
(4) **Who/what will** verify if reference update could be accepted (prepare for commit)

**Comment by g4s8** [comment]
@jeffzhu503 thanks, fixed. Also, added some answeres for questions in wiki page. Please check your email.

**Comment by jeffzhu503** [comment]
Thanks for the quick update.
