### ISSUE TITLE
Build is broken on Ubuntu 20.04

### ISSUE THREAD

**Issue by ChGen** [cqfn/degitx#171]
Current build (commit 9e1566118) is broken on Linux Ubuntu 20.04.1 LTS.
All packages from Ubuntu repositories.
GNU Make 4.2.1
go version go1.13.8 linux/amd64

```
$ make
.....

go test -v ./discovery
discovery/seed.go:12:2: cannot find module providing package cqfn.org/degitx/proto/go/degitxpb
make: *** [Makefile:21: test] Error 1
```

**Comment by stepanvalyavskiy** [comment]
@ivanbukhtiyarov have you done [`make proto`](https://github.com/cqfn/degitx#contributing) before?

**Comment by ChGen** [comment]
@stepanvalyavskiy , yes, with the same error message.

**Comment by ChGen** [comment]
Maybe some documentation update on project setup is required?

**Comment by ivanbukhtiyarov** [comment]
Same on macOS, `reading https://cqfn.org/degitx/proto/go/degitxpb?go-get=1: 404 Not Found` after ``` go get -insecure cqfn.org/degitx/proto/go/degitxpb```

**Comment by g4s8** [comment]
@ivanbukhtiyarov `cqfn.org/degitx` is a local model (see `go.mod`) it's not supposed to fetch it remotely.

**Comment by ivanbukhtiyarov** [comment]
I see. @ChGen try to add the project to GOPATH, it builds successfully for me.

**Comment by ChGen** [comment]
After executing command below I've got another error, after that I executed `make` and it was fully successfull.
`GOPATH="$GOPATH:$PWD" make`

**Comment by ChGen** [comment]
Also, after `git clean -fdx` I still have successful built with regular `make`. I think those results still cached somewhere.
So, there's still some issue with build system.

**Comment by ivanbukhtiyarov** [comment]
WSL 1, ubuntu 20.04 lts, go1.13.8 linux/amd64, protobuf-compiler and all packages from the Ubuntu repo. 

1. make proto
2. go mod tidy
3. make

was built fully successfully. 
@g4s8 I suppose we need to add `go mod tidy` for updating dependencies to the Makefile in the beginning of "all" target  or to the build guide

**Comment by g4s8** [comment]
@ivanbukhtiyarov I tried to reproduce you fix, but it doesn't work. I tried on clean Docker container with:
```
docker run -it --rm -v $PWD:/r golang:1.15
# make proto
# go mod tidy
# make
...
ok  	cqfn.org/degitx/locators	0.002s
go test -v ./discovery
go: finding module for package cqfn.org/degitx/proto/go/degitxpb
discovery/seed.go:12:2: cannot find module providing package cqfn.org/degitx/proto/go/degitxpb: unrecognized import path "cqfn.org/degitx/proto/go/degitxpb": https fetch: Get "https://cqfn.org/degitx/proto/go/degitxpb?go-get=1": x509: certificate is valid for www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com, not cqfn.org
make: *** [Makefile:21: test] Error 1
```

It seems the problem is that go can't find generated proto go files in `proto/go/degitxpb/` (by package ` cqfn.org/degitx/proto/go/degitxpb`)

**Comment by g4s8** [comment]
@ChGen can we close?
