### ISSUE TITLE
Setup internal Gitlab staging environment

### ISSUE THREAD

**Issue by g4s8** [cqfn/degitx#21]
Create Gitlab installation on provided VMs, use `degitx` node as Gitaly service:
 - [x] Configure cluster orchestration tools
 - [x] Find proper documentation and read it
 - [x] Deploy all required components on VMs
 - [x] Deploy Degitx as Gitaly service

**Comment by stepanvalyavskiy** [comment]
Hi, @g4s8 , Gitaly + Degitix are deployed and configured on a single VM.
`/home/stepan/degitx/bin` is degitx binaries location, run it from here.
`/etc/init.d/gitlab start` to start gitlab
`service nginx start` to start nginx
`bundle exec rake gitlab:check RAILS_ENV=production` to chek if evrething are configured and work correctly.

You can access gitlab and check degitx answer via `git push --set-upstream {%FCDN}/{%user_name}/test.git master`

**Comment by g4s8** [comment]
@stepanvalyavskiy thanks a lot
