### ISSUE TITLE
Generate NodeId based on public key

### ISSUE THREAD

**Issue by g4s8** [cqfn/degitx#28]
See section "2.1.1    Locators" of https://central.artipie.com/degit/wp/white-paper-latest.pdf

Consider public and private keys are provided for node (parsed from #27 node configuration). Create a function to generate [multihash](https://multiformats.io/multihash/) node id from public key. Let's create a CLI command `id` to print current node id.

If something is not clear, please use ticket comments to discuss it.

**Comment by stepanvalyavskiy** [comment]
@g4s8 @kirill-h5i Which one hash function should we use for multihas base?
```
	"identity":                  IDENTITY,
	"sha1":                      SHA1,
	"sha2-256":                  SHA2_256,
	"sha2-512":                  SHA2_512,
	"sha3":                      SHA3_512,
	"sha3-224":                  SHA3_224,
	"sha3-256":                  SHA3_256,
	"sha3-384":                  SHA3_384,
	"sha3-512":                  SHA3_512,
	"dbl-sha2-256":              DBL_SHA2_256,
	"murmur3-128":               MURMUR3_128,
	"keccak-224":                KECCAK_224,
	"keccak-256":                KECCAK_256,
	"keccak-384":                KECCAK_384,
	"keccak-512":                KECCAK_512,
	"shake-128":                 SHAKE_128,
	"shake-256":                 SHAKE_256,
	"sha2-256-trunc254-padded":  SHA2_256_TRUNC254_PADDED,
	"x11":                       X11,
	"md5":                       MD5,
	"poseidon-bls12_381-a2-fc1": POSEIDON_BLS12_381_A1_FC1,
```

**Comment by stepanvalyavskiy** [comment]
@g4s8 Which hash function should we use? 

```
	"identity":                  IDENTITY,
	"sha1":                      SHA1,
	"sha2-256":                  SHA2_256,
	"sha2-512":                  SHA2_512,
	"sha3":                      SHA3_512,
	"sha3-224":                  SHA3_224,
	"sha3-256":                  SHA3_256,
	"sha3-384":                  SHA3_384,
	"sha3-512":                  SHA3_512,
	"dbl-sha2-256":              DBL_SHA2_256,
	"murmur3-128":               MURMUR3_128,
	"keccak-224":                KECCAK_224,
	"keccak-256":                KECCAK_256,
	"keccak-384":                KECCAK_384,
	"keccak-512":                KECCAK_512,
	"shake-128":                 SHAKE_128,
	"shake-256":                 SHAKE_256,
	"sha2-256-trunc254-padded":  SHA2_256_TRUNC254_PADDED,
	"x11":                       X11,
	"md5":                       MD5,
	"poseidon-bls12_381-a2-fc1": POSEIDON_BLS12_381_A1_FC1,
```

**Comment by g4s8** [comment]
> @g4s8 Which hash function should we use? 
> 
> ```
> 	"identity":                  IDENTITY,
> 	"sha1":                      SHA1,
> 	"sha2-256":                  SHA2_256,
> 	"sha2-512":                  SHA2_512,
> 	"sha3":                      SHA3_512,
> 	"sha3-224":                  SHA3_224,
> 	"sha3-256":                  SHA3_256,
> 	"sha3-384":                  SHA3_384,
> 	"sha3-512":                  SHA3_512,
> 	"dbl-sha2-256":              DBL_SHA2_256,
> 	"murmur3-128":               MURMUR3_128,
> 	"keccak-224":                KECCAK_224,
> 	"keccak-256":                KECCAK_256,
> 	"keccak-384":                KECCAK_384,
> 	"keccak-512":                KECCAK_512,
> 	"shake-128":                 SHAKE_128,
> 	"shake-256":                 SHAKE_256,
> 	"sha2-256-trunc254-padded":  SHA2_256_TRUNC254_PADDED,
> 	"x11":                       X11,
> 	"md5":                       MD5,
> 	"poseidon-bls12_381-a2-fc1": POSEIDON_BLS12_381_A1_FC1,
> ```

@stepanvalyavskiy I think we can configure it in yaml file and use `SHA1` by default
