### ISSUE TITLE
Describe repository objects update workflow

### ISSUE THREAD

**Issue by g4s8** [cqfn/degitx#3]
Let's investigate how git stores objects (in `.git/objects`) and investigate how objects are updated on different actions. The most [important updates](https://central.artipie.com/degit/wp/white-paper-latest.pdf) for us are:
 - branch create/delete
 - tag create/delete
 - branches update (new commits)
 - ref create/update

**Comment by stepanvalyavskiy** [comment]
@g4s8 Hi, Kirill, this task is done, could we close it?

**Comment by g4s8** [comment]
@stepanvalyavskiy sure, thanks
