### ISSUE TITLE
Create go skeleton

### ISSUE THREAD

**Issue by g4s8** [cqfn/degitx#4]
Create stub go application skeleton, there should be:
 - [x] main function which does nothing
 - [x] test stub which passes
 - [x] CI build and test for pull requests and for master branch (I'd suggest using GitHub actions)
 - [x] Makefile to generate proto files, build and test
 - [x] Style checker configuration and CI integration #19
 - [x] CD: build binaries and upload to release assets on tag in master (I'd suggest goreleaser project to automate build deployment, it can be configured as GitHub action too) #24

**Comment by Michelle99798** [comment]
@stepanvalyavskiy

**Comment by stepanvalyavskiy** [comment]
Hi, @g4s8, I couldn't execute `make proto` locally.
He is log [make_proto_log.txt](https://github.com/cqfn/degitx/files/5363784/make_proto_log.txt)

**Comment by g4s8** [comment]
@stepanvalyavskiy it seems the problem is in Windows `PATH` environment (at `Program Files (x86)`), can you try to modify your path env to get rid of whitespaces and `(` chars before building and try again?

**Comment by g4s8** [comment]
@stepanvalyavskiy just asked a question about your issue: https://stackoverflow.com/q/64317092/1723695

**Comment by g4s8** [comment]
Done

**Comment by stepanvalyavskiy** [comment]
> @stepanvalyavskiy just asked a question about your issue: https://stackoverflow.com/q/64317092/1723695

[The answer](https://stackoverflow.com/a/64318321/13093621) from stackoverflow fixed this.
