### ISSUE TITLE
Initial discovery protocol impl

### ISSUE THREAD

**Issue by g4s8** [cqfn/degitx#44]
IMPORTANT: it's very initial implementation of discovery protocol, it will be changed later. It's needed for implementing other features and for testing, it's not supposed to work on big or unstable network.

Design interfaces and implement primitive discovery protocol:
 - The node starts with provided seed URL (in config)
 - Node keeps all known URLs in memory
 - Node sends `PING` RPC request to all known nodes periodically
 - When node receives new `PING` RPC, it updates known nodes in memory
 - Each node can be a host for seed lists (if configured)

## Seed host
Seed address, interface and port can be specified via CLI options on start. If specified, node starts HTTP server on this port
and returns all known node addresses on request. The format of the list is: `<locator-hex>\s<multiaddr>`\n.

## PING RPC
Node sends own locator (node id) and address (muliaddr format) to all known nodes periodically (each 1 minutes by default)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#49](https://github.com/cqfn/degitx/issues/49) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#49](https://github.com/cqfn/degitx/issues/49), [#53](https://github.com/cqfn/degitx/issues/53) are still not solved.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#53](https://github.com/cqfn/degitx/issues/53) is still not solved; solved: [#49](https://github.com/cqfn/degitx/issues/49).

**Comment by 0pdd** [comment]
@g4s8 all 2 puzzles are solved here: [#49](https://github.com/cqfn/degitx/issues/49), [#53](https://github.com/cqfn/degitx/issues/53).
