### ISSUE TITLE
Move gitlab gRPC logic to another package

### ISSUE THREAD

**Issue by g4s8** [cqfn/degitx#51]
Let's move all code related to gRPC service registration and start up from `degitx.go` of package `degitx` to new package (e.g. `degitx/gitlab`) and provide interface to start and stop it. Also, proto definition package could be changed to `gitlab` name. 

@stepanvalyavskiy please comment here if you have any concerns.

**Comment by stepanvalyavskiy** [comment]
> Let's move all code related to gRPC service registration and start up from `degitx.go` of package `degitx` to new package (e.g. `degitx/gitlab`) and provide interface to start and stop it. Also, proto definition package could be changed to `gitlab` name.
> 
> @stepanvalyavskiy please comment here if you have any concerns.

Probably it would be better not to change proto package to `gitlab`, but use gitaly go generated pb files as dependency and remove all gitaly gRPC from `degitx` proto package. 
@g4s8, what do you think?
