### ISSUE TITLE
Implement front-end health check

### ISSUE THREAD

**Issue by stepanvalyavskiy** [cqfn/degitx#74]
`Gitlab` check `Gitaly` via `google.golang.org/grpc/health/grpc_health_v1` by startup.
If `Gitlab` doesn't get positive health check response, it fails to start.

Let's implement stub health check rpc, that always responses positive.

**Comment by 0pdd** [comment]
@stepanvalyavskiy 2 puzzles [#122](https://github.com/cqfn/degitx/issues/122), [#123](https://github.com/cqfn/degitx/issues/123) are still not solved.
