### ISSUE TITLE
Research for ability to push multiple changes simultaneously

### ISSUE THREAD

**Issue by g4s8** [cqfn/degitx#97]
Let's check if it's possible to optimize to upload multiple changes simultaneously, I'm assuming that it can be done using this approach:
 - upload objects asynchronously, since it has digest naming (check if it's possible)
 - update references synchronously after upload - set references, tags etc

**Comment by stepanvalyavskiy** [comment]
Transaction hook allows us to lock only on ref updates. So this question was answered in context of #76.
@g4s8, I think this ticket could be closed wit merge of #98.
